name:frontend ci

on:
 push:
  branches:["main"]
 pull_request:
  branches:["main"]

jobs:
 builds:
  runs-on:ubuntu-latest

  steps:
   -name:checkout code
    uses:actions/checkout@v4

   -name:install node
    uses:actions/setup-node@v4
      with:
       -version: 18
       cache:"npm"

   -name:npm install
   run:npm install

   -name:test
   run:npm run test -- --watch=fails

   -name:build
   run:npm run build
